export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_NAME = 'SET_NAME'
export const SET_AVATAR = 'SET_AVATAR'
export const SET_ROLES = 'SET_ROLES'
export const SET_ROUTERS = 'SET_ROUTERS'
